package com.building.dao.ifc;

import com.building.model.Building;
import com.building.model.BuildingExample;
import java.util.List;

public interface BuildingDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int countByExample(BuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByExample(BuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insert(Building record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insertSelective(Building record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    List selectByExample(BuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    Building selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExampleSelective(Building record, BuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExample(Building record, BuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKeySelective(Building record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKey(Building record);
}