package com.building.dao.ifc;

import com.building.model.Device;
import com.building.model.DeviceExample;
import java.util.List;

public interface DeviceDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int countByExample(DeviceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByExample(DeviceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insert(Device record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insertSelective(Device record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    List selectByExample(DeviceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExampleSelective(Device record, DeviceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExample(Device record, DeviceExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table device
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKey(Device record);
}