package com.building.dao.ifc;

import com.building.model.RoleHasAutho;
import com.building.model.RoleHasAuthoExample;
import java.util.List;

public interface RoleHasAuthoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    int countByExample(RoleHasAuthoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    int deleteByExample(RoleHasAuthoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    void insert(RoleHasAutho record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    void insertSelective(RoleHasAutho record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    List selectByExample(RoleHasAuthoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    RoleHasAutho selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    int updateByExampleSelective(RoleHasAutho record, RoleHasAuthoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    int updateByExample(RoleHasAutho record, RoleHasAuthoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    int updateByPrimaryKeySelective(RoleHasAutho record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    int updateByPrimaryKey(RoleHasAutho record);
}