package com.building.dao.ifc;

import com.building.model.RoleHasBuilding;
import com.building.model.RoleHasBuildingExample;
import java.util.List;

public interface RoleHasBuildingDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int countByExample(RoleHasBuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByExample(RoleHasBuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insert(RoleHasBuilding record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insertSelective(RoleHasBuilding record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    List selectByExample(RoleHasBuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    RoleHasBuilding selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExampleSelective(RoleHasBuilding record, RoleHasBuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExample(RoleHasBuilding record, RoleHasBuildingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKeySelective(RoleHasBuilding record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_building
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKey(RoleHasBuilding record);
}