package com.building.dao.ifc;

import com.building.model.Schedule;
import com.building.model.ScheduleExample;
import java.util.List;

public interface ScheduleDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int countByExample(ScheduleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByExample(ScheduleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insert(Schedule record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insertSelective(Schedule record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    List selectByExample(ScheduleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    Schedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExampleSelective(Schedule record, ScheduleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExample(Schedule record, ScheduleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKeySelective(Schedule record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table schedule
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKey(Schedule record);
}