package com.building.dao.ifc;

import com.building.model.UserHasRole;
import com.building.model.UserHasRoleExample;
import java.util.List;

public interface UserHasRoleDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int countByExample(UserHasRoleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByExample(UserHasRoleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insert(UserHasRole record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    void insertSelective(UserHasRole record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    List selectByExample(UserHasRoleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    UserHasRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExampleSelective(UserHasRole record, UserHasRoleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByExample(UserHasRole record, UserHasRoleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKeySelective(UserHasRole record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    int updateByPrimaryKey(UserHasRole record);
}