package com.building.model;

import java.util.Date;

public class Autho {
    private String superName;
    
    public String getSuperName() {
        return superName;
    }

    
    public void setSuperName( String superName ) {
        this.superName = superName;
    }

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.autho_name
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private String authoName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.url
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private String url;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.super_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer superId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.description
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.is_del
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.create_time
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.create_user_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.update_time
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column autho.update_user_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer updateUserId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.id
     *
     * @return the value of autho.id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.id
     *
     * @param id the value for autho.id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.autho_name
     *
     * @return the value of autho.autho_name
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public String getAuthoName() {
        return authoName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.autho_name
     *
     * @param authoName the value for autho.autho_name
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setAuthoName(String authoName) {
        this.authoName = authoName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.url
     *
     * @return the value of autho.url
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.url
     *
     * @param url the value for autho.url
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.super_id
     *
     * @return the value of autho.super_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.super_id
     *
     * @param superId the value for autho.super_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setSuperId(Integer superId) {
        this.superId = superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.description
     *
     * @return the value of autho.description
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.description
     *
     * @param description the value for autho.description
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.is_del
     *
     * @return the value of autho.is_del
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.is_del
     *
     * @param isDel the value for autho.is_del
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.create_time
     *
     * @return the value of autho.create_time
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.create_time
     *
     * @param createTime the value for autho.create_time
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.create_user_id
     *
     * @return the value of autho.create_user_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.create_user_id
     *
     * @param createUserId the value for autho.create_user_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.update_time
     *
     * @return the value of autho.update_time
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.update_time
     *
     * @param updateTime the value for autho.update_time
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column autho.update_user_id
     *
     * @return the value of autho.update_user_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column autho.update_user_id
     *
     * @param updateUserId the value for autho.update_user_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }
}