package com.building.model;

import java.util.Date;

public class Building {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.building_name
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private String buildingName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.building_type
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer buildingType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.super_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer superId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.center_lat
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Double centerLat;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.center_lng
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Double centerLng;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column building.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.id
     * @return  the value of building.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.id
     * @param id  the value for building.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.building_name
     * @return  the value of building.building_name
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.building_name
     * @param buildingName  the value for building.building_name
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setBuildingName( String buildingName ) {
        this.buildingName = buildingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.building_type
     * @return  the value of building.building_type
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getBuildingType() {
        return buildingType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.building_type
     * @param buildingType  the value for building.building_type
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setBuildingType( Integer buildingType ) {
        this.buildingType = buildingType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.super_id
     * @return  the value of building.super_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.super_id
     * @param superId  the value for building.super_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setSuperId( Integer superId ) {
        this.superId = superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.is_del
     * @return  the value of building.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.is_del
     * @param isDel  the value for building.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setIsDel( Integer isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.center_lat
     * @return  the value of building.center_lat
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Double getCenterLat() {
        return centerLat;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.center_lat
     * @param centerLat  the value for building.center_lat
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCenterLat( Double centerLat ) {
        this.centerLat = centerLat;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.center_lng
     * @return  the value of building.center_lng
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Double getCenterLng() {
        return centerLng;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.center_lng
     * @param centerLng  the value for building.center_lng
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCenterLng( Double centerLng ) {
        this.centerLng = centerLng;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.create_user_id
     * @return  the value of building.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.create_user_id
     * @param createUserId  the value for building.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.create_time
     * @return  the value of building.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.create_time
     * @param createTime  the value for building.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.update_user_id
     * @return  the value of building.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.update_user_id
     * @param updateUserId  the value for building.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column building.update_time
     * @return  the value of building.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column building.update_time
     * @param updateTime  the value for building.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }
}