package com.building.model;

public class Building {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column building.id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column building.building_name
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private String buildingName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column building.building_type
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer buildingType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column building.super_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer superId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column building.user_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column building.is_del
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer isDel;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column building.id
     *
     * @return the value of building.id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column building.id
     *
     * @param id the value for building.id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column building.building_name
     *
     * @return the value of building.building_name
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column building.building_name
     *
     * @param buildingName the value for building.building_name
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column building.building_type
     *
     * @return the value of building.building_type
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getBuildingType() {
        return buildingType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column building.building_type
     *
     * @param buildingType the value for building.building_type
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setBuildingType(Integer buildingType) {
        this.buildingType = buildingType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column building.super_id
     *
     * @return the value of building.super_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getSuperId() {
        return superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column building.super_id
     *
     * @param superId the value for building.super_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setSuperId(Integer superId) {
        this.superId = superId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column building.user_id
     *
     * @return the value of building.user_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column building.user_id
     *
     * @param userId the value for building.user_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column building.is_del
     *
     * @return the value of building.is_del
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column building.is_del
     *
     * @param isDel the value for building.is_del
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}