package com.building.model;

import java.util.Date;

public class Device {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.device_name
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private String deviceName;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.device_type
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer deviceType;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.state
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer state;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.building_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Long buildingId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.device_no
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private String deviceNo;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column device.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.id
     * @return  the value of device.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.id
     * @param id  the value for device.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.device_name
     * @return  the value of device.device_name
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.device_name
     * @param deviceName  the value for device.device_name
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setDeviceName( String deviceName ) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.device_type
     * @return  the value of device.device_type
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.device_type
     * @param deviceType  the value for device.device_type
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setDeviceType( Integer deviceType ) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.state
     * @return  the value of device.state
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.state
     * @param state  the value for device.state
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setState( Integer state ) {
        this.state = state;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.building_id
     * @return  the value of device.building_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Long getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.building_id
     * @param buildingId  the value for device.building_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setBuildingId( Long buildingId ) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.is_del
     * @return  the value of device.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.is_del
     * @param isDel  the value for device.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setIsDel( Integer isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.device_no
     * @return  the value of device.device_no
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public String getDeviceNo() {
        return deviceNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.device_no
     * @param deviceNo  the value for device.device_no
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setDeviceNo( String deviceNo ) {
        this.deviceNo = deviceNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.create_user_id
     * @return  the value of device.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.create_user_id
     * @param createUserId  the value for device.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.create_time
     * @return  the value of device.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.create_time
     * @param createTime  the value for device.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.update_user_id
     * @return  the value of device.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.update_user_id
     * @param updateUserId  the value for device.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column device.update_time
     * @return  the value of device.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column device.update_time
     * @param updateTime  the value for device.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }
}