package com.building.model;

public class Device {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device.id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device.device_name
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private String deviceName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device.device_type
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer deviceType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device.state
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device.building_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Long buildingId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column device.is_del
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    private Integer isDel;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device.device_name
     *
     * @return the value of device.device_name
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device.device_name
     *
     * @param deviceName the value for device.device_name
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device.device_type
     *
     * @return the value of device.device_type
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device.device_type
     *
     * @param deviceType the value for device.device_type
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device.state
     *
     * @return the value of device.state
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device.state
     *
     * @param state the value for device.state
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device.building_id
     *
     * @return the value of device.building_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Long getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device.building_id
     *
     * @param buildingId the value for device.building_id
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setBuildingId(Long buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column device.is_del
     *
     * @return the value of device.is_del
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column device.is_del
     *
     * @param isDel the value for device.is_del
     *
     * @ibatorgenerated Fri May 22 23:01:52 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}