package com.building.model;

import java.util.Date;

public class Role {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.role_name
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.description
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer isDel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.create_time
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.create_user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.update_time
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role.update_user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer updateUserId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.description
     *
     * @return the value of role.description
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.description
     *
     * @param description the value for role.description
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.is_del
     *
     * @return the value of role.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.is_del
     *
     * @param isDel the value for role.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.create_time
     *
     * @return the value of role.create_time
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.create_time
     *
     * @param createTime the value for role.create_time
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.create_user_id
     *
     * @return the value of role.create_user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.create_user_id
     *
     * @param createUserId the value for role.create_user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.update_time
     *
     * @return the value of role.update_time
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.update_time
     *
     * @param updateTime the value for role.update_time
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role.update_user_id
     *
     * @return the value of role.update_user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role.update_user_id
     *
     * @param updateUserId the value for role.update_user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }
}