package com.building.model;

public class RoleHasBuilding {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_building.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_building.role_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_building.building_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer buildingId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_building.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer isDel;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_building.id
     *
     * @return the value of role_has_building.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_building.id
     *
     * @param id the value for role_has_building.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_building.role_id
     *
     * @return the value of role_has_building.role_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_building.role_id
     *
     * @param roleId the value for role_has_building.role_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_building.building_id
     *
     * @return the value of role_has_building.building_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_building.building_id
     *
     * @param buildingId the value for role_has_building.building_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_building.is_del
     *
     * @return the value of role_has_building.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_building.is_del
     *
     * @param isDel the value for role_has_building.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}