package com.building.model;

public class RoleHasAutho {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_autho.id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_autho.role_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_autho.autho_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer authoId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column role_has_autho.is_del
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private Integer isDel;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_autho.id
     *
     * @return the value of role_has_autho.id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_autho.id
     *
     * @param id the value for role_has_autho.id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_autho.role_id
     *
     * @return the value of role_has_autho.role_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_autho.role_id
     *
     * @param roleId the value for role_has_autho.role_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_autho.autho_id
     *
     * @return the value of role_has_autho.autho_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getAuthoId() {
        return authoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_autho.autho_id
     *
     * @param authoId the value for role_has_autho.autho_id
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setAuthoId(Integer authoId) {
        this.authoId = authoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column role_has_autho.is_del
     *
     * @return the value of role_has_autho.is_del
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column role_has_autho.is_del
     *
     * @param isDel the value for role_has_autho.is_del
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}