package com.building.model;

import java.util.Date;

public class Schedule {

    private String buildingName;
    private String deviceName;
    
    public String getBuildingName() {
        return buildingName;
    }

    
    public void setBuildingName( String buildingName ) {
        this.buildingName = buildingName;
    }

    
    public String getDeviceName() {
        return deviceName;
    }

    
    public void setDeviceName( String deviceName ) {
        this.deviceName = deviceName;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.schedule_date
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Date scheduleDate;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.device_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer deviceId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.change_state
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer changeState;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.is_done
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer isDone;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column schedule.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.id
     * @return  the value of schedule.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.id
     * @param id  the value for schedule.id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.schedule_date
     * @return  the value of schedule.schedule_date
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Date getScheduleDate() {
        return scheduleDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.schedule_date
     * @param scheduleDate  the value for schedule.schedule_date
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setScheduleDate( Date scheduleDate ) {
        this.scheduleDate = scheduleDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.device_id
     * @return  the value of schedule.device_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.device_id
     * @param deviceId  the value for schedule.device_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setDeviceId( Integer deviceId ) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.change_state
     * @return  the value of schedule.change_state
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getChangeState() {
        return changeState;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.change_state
     * @param changeState  the value for schedule.change_state
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setChangeState( Integer changeState ) {
        this.changeState = changeState;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.is_done
     * @return  the value of schedule.is_done
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getIsDone() {
        return isDone;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.is_done
     * @param isDone  the value for schedule.is_done
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setIsDone( Integer isDone ) {
        this.isDone = isDone;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.is_del
     * @return  the value of schedule.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.is_del
     * @param isDel  the value for schedule.is_del
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setIsDel( Integer isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.create_time
     * @return  the value of schedule.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.create_time
     * @param createTime  the value for schedule.create_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.create_user_id
     * @return  the value of schedule.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.create_user_id
     * @param createUserId  the value for schedule.create_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.update_user_id
     * @return  the value of schedule.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.update_user_id
     * @param updateUserId  the value for schedule.update_user_id
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column schedule.update_time
     * @return  the value of schedule.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column schedule.update_time
     * @param updateTime  the value for schedule.update_time
     * @ibatorgenerated  Tue May 26 21:29:16 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }
}