package com.building.model;

public class SmUser {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sm_user.id
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sm_user.login_name
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sm_user.password
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    private String password;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sm_user.id
     *
     * @return the value of sm_user.id
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sm_user.id
     *
     * @param id the value for sm_user.id
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sm_user.login_name
     *
     * @return the value of sm_user.login_name
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sm_user.login_name
     *
     * @param loginName the value for sm_user.login_name
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sm_user.password
     *
     * @return the value of sm_user.password
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sm_user.password
     *
     * @param password the value for sm_user.password
     *
     * @ibatorgenerated Wed May 13 16:52:55 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }
}