package com.building.model;

public class UserHasRole {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_has_role.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_has_role.user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_has_role.role_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user_has_role.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private Integer isDel;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_has_role.id
     *
     * @return the value of user_has_role.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_has_role.id
     *
     * @param id the value for user_has_role.id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_has_role.user_id
     *
     * @return the value of user_has_role.user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_has_role.user_id
     *
     * @param userId the value for user_has_role.user_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_has_role.role_id
     *
     * @return the value of user_has_role.role_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_has_role.role_id
     *
     * @param roleId the value for user_has_role.role_id
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user_has_role.is_del
     *
     * @return the value of user_has_role.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user_has_role.is_del
     *
     * @param isDel the value for user_has_role.is_del
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}