package com.building.model;

import java.util.Date;

public class User {

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.username
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private String username;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.password
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private String password;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.last_login
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Date lastLogin;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.is_online
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Long isOnline;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.is_del
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Integer isDel;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.create_user_id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Integer createUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.create_time
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.update_user_id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Integer updateUserId;
    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.update_time
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.id
     * @return  the value of user.id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.id
     * @param id  the value for user.id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setId( Integer id ) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.username
     * @return  the value of user.username
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.username
     * @param username  the value for user.username
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setUsername( String username ) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.password
     * @return  the value of user.password
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.password
     * @param password  the value for user.password
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setPassword( String password ) {
        this.password = password;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.last_login
     * @return  the value of user.last_login
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.last_login
     * @param lastLogin  the value for user.last_login
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setLastLogin( Date lastLogin ) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.is_online
     * @return  the value of user.is_online
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Long getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.is_online
     * @param isOnline  the value for user.is_online
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setIsOnline( Long isOnline ) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.is_del
     * @return  the value of user.is_del
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.is_del
     * @param isDel  the value for user.is_del
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setIsDel( Integer isDel ) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.create_user_id
     * @return  the value of user.create_user_id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.create_user_id
     * @param createUserId  the value for user.create_user_id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setCreateUserId( Integer createUserId ) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.create_time
     * @return  the value of user.create_time
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.create_time
     * @param createTime  the value for user.create_time
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setCreateTime( Date createTime ) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.update_user_id
     * @return  the value of user.update_user_id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.update_user_id
     * @param updateUserId  the value for user.update_user_id
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setUpdateUserId( Integer updateUserId ) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.update_time
     * @return  the value of user.update_time
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.update_time
     * @param updateTime  the value for user.update_time
     * @ibatorgenerated  Wed May 27 16:47:00 CST 2015
     */
    public void setUpdateTime( Date updateTime ) {
        this.updateTime = updateTime;
    }
}