package com.building.dao.impl;

import com.building.dao.ifc.RoleDAO;
import com.building.model.Role;
import com.building.model.RoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RoleDAOImpl extends SqlMapClientDaoSupport implements RoleDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public RoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int countByExample(RoleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("role.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int deleteByExample(RoleExample example) {
        int rows = getSqlMapClientTemplate().delete("role.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        Role key = new Role();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("role.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void insert(Role record) {
        getSqlMapClientTemplate().insert("role.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void insertSelective(Role record) {
        getSqlMapClientTemplate().insert("role.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public List selectByExample(RoleExample example) {
        List list = getSqlMapClientTemplate().queryForList("role.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public Role selectByPrimaryKey(Integer id) {
        Role key = new Role();
        key.setId(id);
        Role record = (Role) getSqlMapClientTemplate().queryForObject("role.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByExampleSelective(Role record, RoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("role.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByExample(Role record, RoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("role.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByPrimaryKeySelective(Role record) {
        int rows = getSqlMapClientTemplate().update("role.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByPrimaryKey(Role record) {
        int rows = getSqlMapClientTemplate().update("role.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private static class UpdateByExampleParms extends RoleExample {
        private Object record;

        public UpdateByExampleParms(Object record, RoleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}