package com.building.dao.impl;

import com.building.dao.ifc.RoleHasAuthoDAO;
import com.building.model.RoleHasAutho;
import com.building.model.RoleHasAuthoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RoleHasAuthoDAOImpl extends SqlMapClientDaoSupport implements RoleHasAuthoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public RoleHasAuthoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public int countByExample(RoleHasAuthoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("role_has_autho.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public int deleteByExample(RoleHasAuthoExample example) {
        int rows = getSqlMapClientTemplate().delete("role_has_autho.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        RoleHasAutho key = new RoleHasAutho();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("role_has_autho.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void insert(RoleHasAutho record) {
        getSqlMapClientTemplate().insert("role_has_autho.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public void insertSelective(RoleHasAutho record) {
        getSqlMapClientTemplate().insert("role_has_autho.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public List selectByExample(RoleHasAuthoExample example) {
        List list = getSqlMapClientTemplate().queryForList("role_has_autho.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public RoleHasAutho selectByPrimaryKey(Integer id) {
        RoleHasAutho key = new RoleHasAutho();
        key.setId(id);
        RoleHasAutho record = (RoleHasAutho) getSqlMapClientTemplate().queryForObject("role_has_autho.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public int updateByExampleSelective(RoleHasAutho record, RoleHasAuthoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("role_has_autho.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public int updateByExample(RoleHasAutho record, RoleHasAuthoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("role_has_autho.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public int updateByPrimaryKeySelective(RoleHasAutho record) {
        int rows = getSqlMapClientTemplate().update("role_has_autho.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    public int updateByPrimaryKey(RoleHasAutho record) {
        int rows = getSqlMapClientTemplate().update("role_has_autho.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table role_has_autho
     *
     * @ibatorgenerated Tue Jun 02 23:04:46 CST 2015
     */
    private static class UpdateByExampleParms extends RoleHasAuthoExample {
        private Object record;

        public UpdateByExampleParms(Object record, RoleHasAuthoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}