package com.building.dao.impl;

import com.building.dao.ifc.UserHasRoleDAO;
import com.building.model.UserHasRole;
import com.building.model.UserHasRoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserHasRoleDAOImpl extends SqlMapClientDaoSupport implements UserHasRoleDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public UserHasRoleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int countByExample(UserHasRoleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("user_has_role.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int deleteByExample(UserHasRoleExample example) {
        int rows = getSqlMapClientTemplate().delete("user_has_role.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        UserHasRole key = new UserHasRole();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("user_has_role.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void insert(UserHasRole record) {
        getSqlMapClientTemplate().insert("user_has_role.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public void insertSelective(UserHasRole record) {
        getSqlMapClientTemplate().insert("user_has_role.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public List selectByExample(UserHasRoleExample example) {
        List list = getSqlMapClientTemplate().queryForList("user_has_role.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public UserHasRole selectByPrimaryKey(Integer id) {
        UserHasRole key = new UserHasRole();
        key.setId(id);
        UserHasRole record = (UserHasRole) getSqlMapClientTemplate().queryForObject("user_has_role.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByExampleSelective(UserHasRole record, UserHasRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_has_role.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByExample(UserHasRole record, UserHasRoleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("user_has_role.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByPrimaryKeySelective(UserHasRole record) {
        int rows = getSqlMapClientTemplate().update("user_has_role.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    public int updateByPrimaryKey(UserHasRole record) {
        int rows = getSqlMapClientTemplate().update("user_has_role.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table user_has_role
     *
     * @ibatorgenerated Tue May 26 21:29:16 CST 2015
     */
    private static class UpdateByExampleParms extends UserHasRoleExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserHasRoleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}